#!/bin/sh
#
# concat.sh — concatenate libpqcsb source files into a single pqcsb.c
#             for vendoring into language-specific extensions.
#
# Usage: sh scripts/concat.sh
# Output: src/pqcsb.c (single-file build)
#
# The concatenated file is self-contained: include it together with
# include/pqcsb.h and a generated pqcsb_config.h to build libpqcsb
# without CMake.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$ROOT_DIR/src"
OUT="$ROOT_DIR/dist/pqcsb.c"

mkdir -p "$ROOT_DIR/dist"

cat > "$OUT" << 'HEADER'
/*
 * pqcsb.c — Secure memory buffer for cryptographic key material.
 *
 * GENERATED FILE — do not edit directly.
 * Produced by: scripts/concat.sh
 * Origin: libpqcsb (https://github.com/msuliq/libpqcsb)
 *
 * Standalone C library — no external dependencies beyond the C standard library.
 *
 * To use: include this file in your build along with pqcsb.h and a
 * pqcsb_config.h generated by CMake (or hand-written for your platform).
 */

HEADER

# Concatenate in dependency order
for src in \
    "$SRC_DIR/secure_zero.c" \
    "$SRC_DIR/random.c" \
    "$SRC_DIR/pqcsb.c"
do
    name="$(basename "$src")"
    echo "" >> "$OUT"
    echo "/* ================================================================== */" >> "$OUT"
    echo "/* $name */" >> "$OUT"
    echo "/* ================================================================== */" >> "$OUT"
    echo "" >> "$OUT"
    # Strip #include "internal.h" — it's included once at the top
    # Keep the first occurrence, strip subsequent ones
    sed '/#include "internal.h"/d' "$src" >> "$OUT"
done

# Prepend the single internal.h include at the top (after the header comment)
TMPFILE="$(mktemp)"
head -n 16 "$OUT" > "$TMPFILE"
echo '#include "internal.h"' >> "$TMPFILE"
echo "" >> "$TMPFILE"
tail -n +17 "$OUT" >> "$TMPFILE"
mv "$TMPFILE" "$OUT"

echo "Generated: $OUT"
echo "Copy $OUT + include/pqcsb.h + src/internal.h + pqcsb_config.h to vendor."
