name: Sanitizers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  sanitize:
    name: ${{ matrix.sanitizer }} on ${{ matrix.os }}
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        sanitizer: [ address, memory, undefined, thread ]
        exclude:
          - os: macos-latest
            sanitizer: memory
    with:
      os: ${{ matrix.os }}
      compiler: clang
      build_type: Debug
      sanitizer: ${{ matrix.sanitizer }}
      build_tests: true

  asan-malloc-fallback:
    name: AddressSanitizer with malloc fallback
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      compiler: clang
      build_type: Debug
      sanitizer: address
      malloc_fallback: 'ON'
      build_tests: true
